/* =========================================================
   JARVIS OS — polecenia fali W3 (dane): notatki (tagi, foldery, przypinanie, kosz, wersje, zadanie z notatki),
   zadania (powtarzanie, priorytet, podzadania, wiele naraz, eksport ICS), minutniki, rynek, pamięć, pliki, dok, widgety.
   Każda zmiana danych ma „Cofnij”; zbiorowe usuwanie — zgoda (docs/spec/06, 07, 08, 05).
   ========================================================= */
'use strict';
(() => {
const R = J.registry, { ok, fail } = R, norm = J.norm, K = J.cmdKit;
const { findNote, findTask, cut, noteRow, taskRow } = K;
const NOTE = { type: 'string', description: 'id albo fragment tytułu notatki; "current" = otwarta' };
const TASK = { type: 'string', description: 'id albo fragment treści zadania' };
const undoable = ids => ids.forEach(id => { R.get(id).undoable = true; });
const noteNow = async q => { if (norm(q) === 'current' || /^(ta|tej|te|to)( notatk\w*)?$/.test(norm(q))) { const st = J.apps.notes?.state?.(J.wm.ctx('notes')); if (st?.noteId) q = st.noteId; } return findNote(q); };
const cleanTag = t => norm(t).replace(/^#/, '').replace(/[^a-z0-9_-]/g, '').slice(0, 24);

/* =================== NOTATKI =================== */
R.add({ id: 'notes_tag', group: 'Notatki', label: 'Tagi notatki', description: 'Dodaje (add) lub usuwa (remove) tagi notatki (małe litery, bez spacji, maks. 10).', writes: ['notes'],
  args: { type: 'object', properties: { note: NOTE, add: { type: 'array', items: { type: 'string', maxLength: 24 } }, remove: { type: 'array', items: { type: 'string' } } }, required: ['note'] },
  examples: ['dodaj tag {add} do notatki {note}', 'oznacz notatke {note} tagiem {add}', 'usun tag {remove} z notatki {note}'],
  parse(raw, n) { let m; if ((m = /^(?:dodaj tag|oznacz tagiem)\s+#?(\S+)\s+(?:do|dla)\s+(?:notatki\s+)?(.+)$/.exec(n))) return { args: { note: raw.slice(n.lastIndexOf(m[2])), add: [m[1]] }, score: 30 }; if ((m = /^oznacz notatke\s+(.+?)\s+tagiem\s+#?(\S+)$/.exec(n))) return { args: { note: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), add: [m[2]] }, score: 30 }; if ((m = /^usun tag\s+#?(\S+)\s+z\s+(?:notatki\s+)?(.+)$/.exec(n))) return { args: { note: raw.slice(n.lastIndexOf(m[2])), remove: [m[1]] }, score: 30 }; if ((m = /^dodaj tag\s+#?(\S+)\s+do tej notatki$/.exec(n))) return { args: { note: 'current', add: [m[1]] }, score: 30 }; return null; },
  async run({ note, add = [], remove = [] }) { const f = await noteNow(note); if (f.err) return f.err; const n = f.note, prev = [...n.tags]; const rm = new Set(remove.map(cleanTag)); n.tags = [...new Set([...n.tags.filter(t => !rm.has(t)), ...add.map(cleanTag).filter(Boolean)])].slice(0, 10); J.save(); J.emit('notes', n.id); return ok(noteRow(n), 'Tagi „' + n.title + '”: ' + (n.tags.map(t => '#' + t).join(' ') || 'brak') + '.', null, () => { n.tags = prev; J.save(); J.emit('notes', n.id); }); } });
R.add({ id: 'notes_pin', group: 'Notatki', label: 'Przypnij notatkę', description: 'Przypina notatkę na górze listy (on=false odpina).', writes: ['notes'],
  args: { type: 'object', properties: { note: NOTE, on: { type: 'boolean' } }, required: ['note'] },
  examples: ['przypnij notatke {note}', 'odepnij notatke {note}', 'przypnij te notatke'],
  parse(raw, n) { const m = /^(przypnij|odepnij)\s+(?:notatke|notatka)\s+(.+)$/.exec(n) || /^(przypnij|odepnij)\s+(te notatke)$/.exec(n); return m ? { args: { note: /^te notatke$/.test(m[2]) ? 'current' : raw.slice(n.lastIndexOf(m[2])), on: m[1] === 'przypnij' }, score: 35 } : null; },
  async run({ note, on = true }) { const f = await noteNow(note); if (f.err) return f.err; const n = f.note, was = n.pinned; n.pinned = on; J.save(); J.emit('notes', n.id); return ok(noteRow(n), (on ? 'Przypiąłem' : 'Odpiąłem') + ' notatkę „' + n.title + '”.', null, () => { n.pinned = was; J.save(); J.emit('notes', n.id); }); } });
R.add({ id: 'notes_duplicate', group: 'Notatki', label: 'Duplikuj notatkę', description: 'Tworzy kopię notatki z dopiskiem „(kopia)” (te same tagi i folder).', writes: ['notes'],
  args: { type: 'object', properties: { note: NOTE }, required: ['note'] },
  examples: ['zduplikuj notatke {note}', 'duplikuj notatke {note}', 'zrob kopie notatki {note}', 'skopiuj notatke {note}'],
  async run({ note }) { const f = await noteNow(note); if (f.err) return f.err; const s = f.note, c = J.notes.add(s.title + ' (kopia)', s.body, { tags: [...s.tags], folder: s.folder }); return ok(noteRow(c), 'Utworzyłem kopię „' + c.title + '”.', { highlight: 'notes' }, () => J.notes.remove(c.id)); } });
R.add({ id: 'notes_trash', group: 'Notatki', label: 'Kosz notatek', description: 'Lista notatek w koszu (usunięte w ciągu 30 dni, można przywrócić). show=true otwiera kosz w Notatniku.', idempotent: true, reads: ['notes'],
  args: { type: 'object', properties: { show: { type: 'boolean' } } },
  examples: ['co jest w koszu', 'pokaz kosz', 'kosz notatek', 'pokaz usuniete notatki', 'ktore notatki usunalem'],
  run({ show }) { const l = J.notes.trashed(); if (show) J.wm.open('notes', { view: 'trash' }); return ok({ notes: l.map(n => ({ id: n.id, title: n.title, deleted: new Date(n.deleted).toISOString() })) }, l.length ? 'W koszu (' + l.length + '): ' + l.slice(0, 8).map(n => '„' + n.title + '”').join(', ') + '.' : 'Kosz jest pusty.'); } });
R.add({ id: 'notes_restore', group: 'Notatki', label: 'Przywróć notatkę z kosza', description: 'Przywraca notatkę z kosza.', writes: ['notes'],
  args: { type: 'object', properties: { note: { type: 'string', description: 'id albo tytuł notatki w koszu' } }, required: ['note'] },
  examples: ['przywroc notatke {note}', 'przywroc z kosza notatke {note}', 'odzyskaj notatke {note}', 'wyciagnij z kosza notatke {note}'],
  parse(raw, n) { const m = /^(?:przywroc|odzyskaj|wyciagnij)(?: z kosza)?\s+(?:usunieta\s+)?notatke\s+(.+?)(?:\s+z kosza)?$/.exec(n); return m ? { args: { note: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length) }, score: 35 } : null; },
  run({ note }) { const q = norm(note), l = J.notes.trashed(), n = l.find(x => x.id === note) || l.find(x => norm(x.title) === q) || l.find(x => norm(x.title).includes(q)); if (!n) return fail('NOT_FOUND', 'W koszu nie ma notatki „' + note + '”.' + (l.length ? ' Są: ' + l.slice(0, 6).map(x => '„' + x.title + '”').join(', ') + '.' : ' Kosz jest pusty.')); J.notes.restore(n.id); return ok(noteRow(n), 'Przywróciłem notatkę „' + n.title + '”.', { highlight: 'notes' }, () => J.notes.trash(n.id)); } });
R.add({ id: 'notes_empty_trash', group: 'Notatki', label: 'Opróżnij kosz', description: 'Trwale usuwa wszystkie notatki z kosza. Nieodwracalne — wymaga potwierdzenia.', risk: 'confirm', writes: ['notes'], confirmText: () => 'Opróżnić kosz (' + J.notes.trashed().length + ' ' + J.pl(J.notes.trashed().length, 'notatka', 'notatki', 'notatek') + ')? Tego nie da się cofnąć.',
  examples: ['oproznij kosz', 'oproznij kosz notatek', 'usun na zawsze notatki z kosza', 'wyczysc kosz'],
  run() { const l = J.notes.trashed(); if (!l.length) return ok({ removed: 0 }, 'Kosz jest pusty.'); l.forEach(n => J.notes.remove(n.id)); return ok({ removed: l.length }, 'Opróżniłem kosz (' + l.length + ').'); } });
R.add({ id: 'notes_versions', group: 'Notatki', label: 'Wersje notatki', description: 'Lista zapisanych wersji notatki (maks. 20; zapis przed każdą zmianą przez Jarvisa i co ≥ 5 min pisania).', idempotent: true, reads: ['notes'],
  args: { type: 'object', properties: { note: NOTE } , required: ['note'] },
  examples: ['pokaz wersje notatki {note}', 'wersje notatki {note}', 'historia zmian notatki {note}', 'co sie zmienialo w tej notatce'],
  parse(raw, n) { if (/^(co sie zmienialo w tej notatce|historia zmian tej notatki|wersje tej notatki)$/.test(n)) return { args: { note: 'current' }, score: 35 }; return null; },
  async run({ note }) { const f = await noteNow(note); if (f.err) return f.err; const l = await J.notes.versions(f.note.id); return ok({ id: f.note.id, versions: l.map(v => ({ vid: v.vid, ts: new Date(v.ts).toISOString(), by: v.by, words: v.body.trim().split(/\s+/).filter(Boolean).length })) }, l.length ? '„' + f.note.title + '” — wersje (' + l.length + '): ' + l.slice(-6).reverse().map(v => new Date(v.ts).toLocaleString('pl-PL', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) + (v.by === 'jarvis' ? ' (przed zmianą Jarvisa)' : '')).join('; ') + '.' : 'Notatka „' + f.note.title + '” nie ma jeszcze zapisanych wersji.'); } });
R.add({ id: 'notes_revert', group: 'Notatki', label: 'Przywróć wersję notatki', description: 'Przywraca wersję notatki (version = id wersji albo "previous"). Bieżąca treść staje się nową wersją, więc można wrócić.', writes: ['notes'],
  args: { type: 'object', properties: { note: NOTE, version: { type: 'string', description: 'id wersji albo "previous"' } }, required: ['note', 'version'] },
  examples: ['przywroc poprzednia wersje notatki {note}', 'wroc do starej tresci notatki {note}', 'cofnij notatke {note} do poprzedniej wersji'],
  parse(raw, n) { let m; if ((m = /^(?:przywroc poprzednia wersje|cofnij do poprzedniej wersji)\s+(?:notatki\s+)?(.+)$/.exec(n))) return { args: { note: raw.slice(n.lastIndexOf(m[1])), version: 'previous' }, score: 35 }; if (/^(wroc do starej tresci tej notatki|przywroc poprzednia wersje tej notatki)$/.test(n)) return { args: { note: 'current', version: 'previous' }, score: 35 }; return null; },
  async run({ note, version }) { const f = await noteNow(note); if (f.err) return f.err; const n = f.note, l = await J.notes.versions(n.id); if (!l.length) return fail('NOT_FOUND', 'Notatka „' + n.title + '” nie ma zapisanych wersji.'); const v = version === 'previous' ? l[l.length - 1] : l.find(x => x.vid === version); if (!v) return fail('NOT_FOUND', 'Nie ma takiej wersji.'); const snap = { title: n.title, body: n.body, ts: n.ts }; await J.notes.version(n, 'restore'); n.title = v.title; n.body = v.body; n.ts = Date.now(); J.save(); J.emit('notes', n.id); return ok(noteRow(n), 'Przywróciłem wersję z ' + new Date(v.ts).toLocaleString('pl-PL', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) + '.', { highlight: 'notes' }, () => { Object.assign(n, snap); J.save(); J.emit('notes', n.id); }); } });
R.add({ id: 'notes_to_task', group: 'Notatki', label: 'Zadanie z notatki', description: 'Tworzy zadanie z notatki (treść = tytuł) albo z jej linii (line); zadanie pamięta notatkę (ikona 📝 w Harmonogramie).', writes: ['tasks'],
  args: { type: 'object', properties: { note: NOTE, line: { type: 'string' }, time: { type: 'string', format: 'time' }, date: { type: 'string', format: 'date' } }, required: ['note'] },
  examples: ['zrob zadanie z notatki {note}', 'dodaj notatke {note} do harmonogramu na {date}', 'przypomnij mi o notatce {note} o {time}'],
  parse(raw, n) { let m; if ((m = /^(?:zrob|utworz) zadanie z notatki\s+(.+?)(?:\s+na\s+(.+))?$/.exec(n))) { const d = m[2] ? J.nlp.date(m[2]) || J.nlp.date('w ' + m[2]) : null; return { args: { note: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), ...(d ? { date: d } : {}) }, score: 35 }; } if ((m = /^przypomnij mi o notatce\s+(.+?)\s+o\s+(.+)$/.exec(n))) return { args: { note: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), time: J.nlp.time('o ' + m[2]) || undefined }, score: 35 }; return null; },
  async run({ note, line, time, date }) { const f = await noteNow(note); if (f.err) return f.err; const n = f.note, text = line ? String(line).replace(/^[-•*\s]+/, '').trim() : n.title; const t = J.tasks.add(time || '', text || n.title, date || J.today(), { note: n.id }); return ok(taskRow(t), 'Dodałem zadanie „' + t.text + '” (' + (t.date === J.today() ? 'dziś' : t.date) + (t.time ? ' o ' + t.time : '') + ') z notatki „' + n.title + '”.', { highlight: 'schedule' }, () => { J.state.tasks = J.state.tasks.filter(x => x !== t); J.save(); J.emit('tasks'); }); } });
R.add({ id: 'notes_folder', group: 'Notatki', label: 'Folder notatki', description: 'Przenosi notatkę do folderu (jeden poziom; folder powstaje sam). folder="" wyjmuje z folderu.', writes: ['notes'],
  args: { type: 'object', properties: { note: NOTE, folder: { type: 'string', maxLength: 40 } }, required: ['note', 'folder'] },
  examples: ['przenies notatke {note} do folderu {folder}', 'wloz notatke {note} do {folder}', 'wyjmij notatke {note} z folderu'],
  parse(raw, n) { let m; if ((m = /^(?:przenies|wloz|wrzuc)\s+(?:notatke\s+)?(.+?)\s+do folderu\s+(.+)$/.exec(n))) return { args: { note: /^(te|ta) notatke$/.test(m[1]) ? 'current' : raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), folder: raw.slice(n.lastIndexOf(m[2])) }, score: 35 }; if ((m = /^wyjmij\s+(?:notatke\s+)?(.+?)\s+z folderu$/.exec(n))) return { args: { note: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), folder: '' }, score: 35 }; return null; },
  async run({ note, folder }) { const f = await noteNow(note); if (f.err) return f.err; const n = f.note, prev = n.folder; n.folder = String(folder || '').trim().slice(0, 40); J.save(); J.emit('notes', n.id); return ok(noteRow(n), n.folder ? '„' + n.title + '” jest teraz w folderze „' + n.folder + '”.' : '„' + n.title + '” poza folderami.', null, () => { n.folder = prev; J.save(); J.emit('notes', n.id); }); } });
undoable(['notes_tag', 'notes_pin', 'notes_duplicate', 'notes_restore', 'notes_revert', 'notes_to_task', 'notes_folder']);

/* =================== ZADANIA =================== */
const RULES = ['none', 'daily', 'weekdays', 'weekly', 'monthly', 'every_n_days'];
const ruleTxt = r => !r || r.rule === 'none' ? 'bez powtarzania' : { daily: 'codziennie', weekdays: 'w dni robocze', weekly: 'co tydzień' + (r.days?.length ? ' (' + r.days.join(', ') + ')' : ''), monthly: 'co miesiąc', every_n_days: 'co ' + r.n + ' dni' }[r.rule] + (r.until ? ' do ' + r.until : '');
R.add({ id: 'tasks_repeat', group: 'Zadania i czas', label: 'Powtarzanie zadania', description: 'Ustawia powtarzanie: daily, weekdays, weekly (days: pn…nd), monthly, every_n_days (n); until = data końca; none = wyłącz. Po odhaczeniu powstaje następne wystąpienie.', writes: ['tasks'],
  args: { type: 'object', properties: { task: TASK, rule: { type: 'string', enum: RULES }, days: { type: 'array', items: { type: 'string', enum: ['pn', 'wt', 'sr', 'cz', 'pt', 'so', 'nd'] } }, n: { type: 'integer', minimum: 2, maximum: 365 }, until: { type: 'string', format: 'date' } }, required: ['task', 'rule'] },
  examples: ['powtarzaj {task} codziennie', '{task} powtarzaj w poniedzialki i czwartki', 'przestan powtarzac {task}', 'powtarzaj {task} co tydzien'],
  parse(raw, n) { let m; if ((m = /^przestan powtarzac\s+(.+)$/.exec(n))) return { args: { task: raw.slice(n.indexOf(m[1])), rule: 'none' }, score: 35 }; if ((m = /^powtarzaj\s+(.+?)\s+((?:codziennie|w dni robocze|co tydzien|co miesiac|co \d+ dni|w (?:poniedzialki|wtorki|srody|czwartki|piatki|soboty|niedziele).*))$/.exec(n)) || (m = /^(.+?)\s+powtarzaj\s+(.+)$/.exec(n))) { const r = J.nlp.repeat(m[2]); if (r) return { args: { task: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), ...r }, score: 35 }; } if ((m = /^(.+?)\s+ma wracac\s+(codziennie|co tydzien|co miesiac)$/.exec(n))) return { args: { task: raw.slice(0, m[1].length), ...J.nlp.repeat(m[2]) }, score: 30 }; return null; },
  async run({ task, rule, days, n, until }) { const f = await findTask(task); if (f.err) return f.err; const t = f.task, prev = { repeat: t.repeat, seriesId: t.seriesId }; t.repeat = rule === 'none' ? null : { rule, ...(days?.length ? { days } : {}), ...(n ? { n } : {}), ...(until ? { until } : {}) }; if (t.repeat && !t.seriesId) t.seriesId = t.id; J.save(); J.emit('tasks'); return ok(taskRow(t), '„' + t.text + '”: ' + ruleTxt(t.repeat) + '.', null, () => { Object.assign(t, prev); J.save(); J.emit('tasks'); }); } });
R.add({ id: 'tasks_priority', group: 'Zadania i czas', label: 'Priorytet zadania', description: 'Ustawia priorytet zadania: high (pilne, na górze listy), normal, low.', writes: ['tasks'],
  args: { type: 'object', properties: { task: TASK, priority: { type: 'string', enum: ['high', 'normal', 'low'] } }, required: ['task', 'priority'] },
  examples: ['priorytet wysoki dla {task}', 'ustaw wysoki priorytet dla {task}', '{task} jest pilne', '{task} moze poczekac'],
  parse(raw, n) { let m; if ((m = /^(?:ustaw\s+)?(wysoki|niski|normalny) priorytet (?:dla\s+)?(.+)$/.exec(n)) || (m = /^priorytet (wysoki|niski|normalny) dla\s+(.+)$/.exec(n))) return { args: { task: raw.slice(n.lastIndexOf(m[2])), priority: { wysoki: 'high', niski: 'low', normalny: 'normal' }[m[1]] }, score: 35 }; if ((m = /^(.+?)\s+(?:jest|to) (pilne|pilny|pilna|wazne)$/.exec(n))) return { args: { task: raw.slice(0, m[1].length), priority: 'high' }, score: 25 }; if ((m = /^(.+?)\s+moze poczekac$/.exec(n))) return { args: { task: raw.slice(0, m[1].length), priority: 'low' }, score: 25 }; return null; },
  async run({ task, priority }) { const f = await findTask(task); if (f.err) return f.err; const t = f.task, prev = t.priority; t.priority = priority; J.tasks.sort(); J.save(); J.emit('tasks'); return ok(taskRow(t), '„' + t.text + '”: priorytet ' + { high: 'wysoki', normal: 'zwykły', low: 'niski' }[priority] + '.', null, () => { t.priority = prev; J.tasks.sort(); J.save(); J.emit('tasks'); }); } });
R.add({ id: 'tasks_subtask', group: 'Zadania i czas', label: 'Podzadania', description: 'Dodaje (add), odhacza (check), odznacza (uncheck) lub usuwa (remove) podzadanie (jeden poziom, maks. 20).', writes: ['tasks'],
  args: { type: 'object', properties: { task: TASK, op: { type: 'string', enum: ['add', 'check', 'uncheck', 'remove'] }, text: { type: 'string', maxLength: 120 } }, required: ['task', 'op', 'text'] },
  examples: ['do {task} dodaj podzadanie {text}', 'dodaj podzadanie {text} do {task}', 'odhacz {text} w {task}', 'usun podzadanie {text} z {task}'],
  parse(raw, n) { let m; if ((m = /^do\s+(.+?)\s+dodaj podzadanie\s+(.+)$/.exec(n))) return { args: { task: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), op: 'add', text: raw.slice(n.lastIndexOf(m[2])) }, score: 35 }; if ((m = /^dodaj podzadanie\s+(.+?)\s+do\s+(.+)$/.exec(n))) return { args: { task: raw.slice(n.lastIndexOf(m[2])), op: 'add', text: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length) }, score: 35 }; if ((m = /^(odhacz|usun podzadanie)\s+(.+?)\s+(?:w|z)\s+(.+)$/.exec(n)) && J.state.tasks.some(t => t.subtasks?.some(s => norm(s.text).includes(m[2])))) return { args: { task: raw.slice(n.lastIndexOf(m[3])), op: m[1] === 'odhacz' ? 'check' : 'remove', text: raw.slice(n.indexOf(m[2]), n.indexOf(m[2]) + m[2].length) }, score: 36 }; return null; },
  async run({ task, op, text }) { const f = await findTask(task); if (f.err) return f.err; const t = f.task, prev = JSON.parse(JSON.stringify(t.subtasks)); if (op === 'add') { if (t.subtasks.length >= 20) return fail('LIMIT', 'Maksymalnie 20 podzadań.'); t.subtasks.push({ id: J.uid(), text: String(text).trim(), done: false }); } else { const q = norm(text), s = t.subtasks.find(x => norm(x.text) === q) || t.subtasks.find(x => norm(x.text).includes(q)); if (!s) return fail('NOT_FOUND', '„' + t.text + '” nie ma podzadania „' + text + '”.'); if (op === 'remove') t.subtasks = t.subtasks.filter(x => x !== s); else s.done = op === 'check'; } J.save(); J.emit('tasks'); const d = t.subtasks.filter(s => s.done).length; return ok(taskRow(t), '„' + t.text + '”: podzadania ' + d + '/' + t.subtasks.length + '.' + (t.subtasks.length && d === t.subtasks.length && !t.done ? ' Wszystkie zrobione — odhaczyć też „' + t.text + '”?' : ''), null, () => { t.subtasks = prev; J.save(); J.emit('tasks'); }); } });
const dayOf = s => { const n = norm(s || ''); if (/^(dzis|dzisiaj|dzisiejsze|z dzis)$/.test(n)) return J.today(); if (/^(overdue|zalegle)$/.test(n)) return 'overdue'; return J.nlp.date(s) || J.nlp.date('w ' + s) || (/^\d{4}-\d{2}-\d{2}$/.test(s) ? s : null); };
R.add({ id: 'tasks_move_many', group: 'Zadania i czas', label: 'Przenieś wiele zadań', description: 'Przenosi zadania z dnia (from: dziś, jutro, data, overdue = zaległe) na inny dzień (to). only_open (domyślnie true) = tylko niezrobione. Jedno „Cofnij” cofa całość.', writes: ['tasks'],
  args: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string', format: 'date' }, only_open: { type: 'boolean' } }, required: ['from', 'to'] },
  examples: ['przenies (wszystkie )?dzisiejsze na jutro', 'przesun zalegle na dzis', 'przeloz niezrobione na poniedzialek'],
  parse(raw, n) { let m; if ((m = /^(?:przenies|przesun|przeloz)\s+(?:wszystkie\s+)?(dzisiejsze|zalegle|niezrobione|zadania z dzis|wszystko z dzis|dzisiejsze zadania)(?:\s+zadania)?\s+na\s+(.+)$/.exec(n))) { const to = m[2] === 'dzis' ? J.today() : J.nlp.date(m[2]) || J.nlp.date('w ' + m[2]); if (to) return { args: { from: /zalegle/.test(m[1]) ? 'overdue' : 'dzis', to }, score: 40 }; } return null; },
  run({ from, to, only_open = true }) { const src = dayOf(from); if (!src) return fail('INVALID_ARGS', 'Nie rozumiem dnia „' + from + '”.'); const dst = dayOf(to) || to; const l = J.state.tasks.filter(t => (src === 'overdue' ? !t.done && t.date < J.today() : t.date === src) && (!only_open || !t.done)); if (!l.length) return ok({ moved: 0 }, 'Nie ma zadań do przeniesienia.'); const prev = l.map(t => ({ t, date: t.date, fired: t.fired })); l.forEach(t => { t.date = dst; t.fired = false; }); J.tasks.sort(); J.save(); J.emit('tasks'); return ok({ moved: l.length, to: dst }, 'Przeniosłem ' + l.length + ' ' + J.pl(l.length, 'zadanie', 'zadania', 'zadań') + ' na ' + dst + '.', null, () => { prev.forEach(p => { p.t.date = p.date; p.t.fired = p.fired; }); J.tasks.sort(); J.save(); J.emit('tasks'); }); } });
R.add({ id: 'tasks_clear_done', group: 'Zadania i czas', label: 'Usuń zrobione', description: 'Usuwa zrobione zadania z zakresu (today, week, all). Zbiorowe usuwanie — wymaga zgody; „Cofnij” przez 10 minut.', risk: 'confirm', writes: ['tasks'], confirmText: a => 'Usunąć zrobione zadania (' + ({ today: 'dziś', week: 'ten tydzień', all: 'wszystkie' }[a.range] || a.range) + ')?',
  args: { type: 'object', properties: { range: { type: 'string', enum: ['today', 'week', 'all'] } }, required: ['range'] },
  examples: ['usun zrobione zadania', 'wyczysc zrobione z tego tygodnia', 'posprzataj ukonczone', 'usun zrobione zadania z tygodnia'],
  parse(raw, n) { if (/^(usun|wyczysc|posprzataj)\s+(zrobione|ukonczone|odhaczone)( zadania)?( z (tego )?tygodnia)?$|^posprzataj liste z odhaczonych$/.test(n)) return { args: { range: /tygodni/.test(n) ? 'week' : 'all' }, score: 35 }; return null; },
  run({ range }) { const today = J.today(), wk = (() => { const d = new Date(); d.setDate(d.getDate() - 7); return d.toISOString().slice(0, 10); })(); const l = J.state.tasks.filter(t => t.done && (range === 'all' || (range === 'today' ? t.date === today : t.date >= wk && t.date <= today))); if (!l.length) return ok({ removed: 0 }, 'Nie ma zrobionych zadań do usunięcia.'); J.state.tasks = J.state.tasks.filter(t => !l.includes(t)); J.save(); J.emit('tasks'); return ok({ removed: l.length }, 'Usunąłem ' + l.length + ' ' + J.pl(l.length, 'zrobione zadanie', 'zrobione zadania', 'zrobionych zadań') + '.', null, () => { J.state.tasks.push(...l.filter(t => !J.state.tasks.includes(t))); J.tasks.sort(); J.save(); J.emit('tasks'); }); } });
R.add({ id: 'tasks_export_ics', group: 'Zadania i czas', label: 'Eksport do kalendarza', description: 'Zapisuje zadania z zakresu (today, week, month, all) jako plik .ics do pobrania (powtarzanie jako RRULE).', idempotent: true, reads: ['tasks'],
  args: { type: 'object', properties: { range: { type: 'string', enum: ['today', 'week', 'month', 'all'] } }, required: ['range'] },
  examples: ['(wyeksportuj|eksportuj) zadania do (kalendarza|ics)', 'zapisz tydzien jako ics', 'eksport zadan na miesiac'],
  parse(raw, n) { if (/^(wy)?eksportuj zadania do (kalendarza|ics|pliku ics)$|^eksport zadan( na (tydzien|miesiac))?$|^zapisz (tydzien|miesiac|zadania) jako ics$|chce te zadania w kalendarzu/.test(n)) return { args: { range: /tydzien/.test(n) ? 'week' : /miesiac/.test(n) ? 'month' : 'all' }, score: 35 }; return null; },
  run({ range }) { const today = J.today(), plus = k => { const d = new Date(); d.setDate(d.getDate() + k); return d.toISOString().slice(0, 10); }; const l = J.state.tasks.filter(t => range === 'all' || (range === 'today' ? t.date === today : t.date >= today && t.date <= plus(range === 'week' ? 7 : 31))); const ics = J.ics.export(l); try { const a = J.h('a', { href: URL.createObjectURL(new Blob([ics], { type: 'text/calendar' })), download: 'jarvis-zadania-' + today + '.ics' }); a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1500); } catch (e) { } return ok({ count: l.length, ics }, 'Zapisałem ' + l.length + ' ' + J.pl(l.length, 'zadanie', 'zadania', 'zadań') + ' do pliku .ics (pobranie).'); } });
undoable(['tasks_repeat', 'tasks_priority', 'tasks_subtask', 'tasks_move_many', 'tasks_clear_done']);

/* =================== MINUTNIKI =================== */
R.add({ id: 'timer_list', group: 'Zadania i czas', label: 'Lista minutników', description: 'Wszystkie działające minutniki (maks. 5) z czasem do końca.', idempotent: true, reads: ['timer'],
  examples: ['lista minutnikow', 'jakie minutniki dzialaja', 'pokaz liste minutnikow', 'ile zostalo na minutnikach'],
  parse(raw, n) { return /^(pokaz )?(liste|lista) minutnikow$|^jakie minutniki (dzialaja|sa wlaczone)$|^ile zostalo na minutnikach$/.test(n) ? { args: {}, score: 40 } : null; },
  run() { const l = J.timers.all(); return ok({ timers: l.map(t => ({ label: t.label, left_s: Math.round(t.left() / 1000), paused: t.paused })) }, l.length ? l.map(t => t.label + ': ' + t.fmt(t.left()) + (t.paused ? ' (wstrzymany)' : '')).join('; ') + '.' : 'Żaden minutnik nie działa.'); } });

/* =================== RYNEK =================== */
R.add({ id: 'market_watchlist', group: 'Dane', label: 'Lista obserwowanych', description: 'Dodaje (add) lub usuwa (remove) kryptowalutę z listy w Monitorze rynku albo ją zwraca (list). Maks. 12. Tylko podgląd — żadnego handlu.', writes: ['settings'],
  args: { type: 'object', properties: { op: { type: 'string', enum: ['add', 'remove', 'list'] }, symbol: { type: 'string', maxLength: 12 } }, required: ['op'] },
  examples: ['dodaj {symbol} do obserwowanych', 'usun {symbol} z rynku', 'jakie kryptowaluty obserwuje', 'nie chce widziec {symbol} w rynku'],
  parse(raw, n) { let m; if ((m = /^dodaj\s+(\S+)\s+do (obserwowanych|rynku|monitora rynku)$/.exec(n))) return { args: { op: 'add', symbol: m[1] }, score: 35 }; if ((m = /^(?:usun)\s+(\S+)\s+z (obserwowanych|rynku|monitora rynku)$/.exec(n)) || (m = /^nie chce (?:juz )?widziec\s+(\S+)\s+w rynku$/.exec(n))) return { args: { op: 'remove', symbol: m[1] }, score: 35 }; if (/^(jakie kryptowaluty obserwuje|lista obserwowanych|co obserwuje na rynku)$/.test(n)) return { args: { op: 'list' }, score: 35 }; return null; },
  run({ op, symbol }) {
    const cur = J.market.COINS.map(c => c.sym);
    if (op === 'list') return ok({ symbols: cur }, 'Obserwuję: ' + cur.join(', ') + '.');
    const sym = (J.cmdKit.coinOf?.(symbol) || String(symbol || '').toUpperCase()).replace(/[^A-Z0-9]/g, ''); if (!sym) return fail('INVALID_ARGS', 'Podaj symbol, np. DOGE.');
    const alias = { DOGECOINA: 'DOGE', DOGECOIN: 'DOGE', RIPPLE: 'XRP', CARDANO: 'ADA', POLKADOT: 'DOT' }[sym] || sym;
    if (op === 'add') { if (cur.includes(alias)) return ok({ symbols: cur }, alias + ' już jest na liście.'); if (cur.length >= 12) return fail('LIMIT', 'Maksymalnie 12 walut — usuń którąś.'); if (!J.market.KNOWN[alias]) return fail('NOT_FOUND', 'Nie znam waluty „' + symbol + '”. Znane: ' + Object.keys(J.market.KNOWN).join(', ') + '.'); const l = J.market.setWatch([...cur, alias]); return ok({ symbols: l }, 'Dodałem ' + alias + ' do obserwowanych.', { highlight: 'market' }, () => J.market.setWatch(cur)); }
    if (!cur.includes(alias)) return fail('NOT_FOUND', alias + ' nie jest obserwowany.'); if (cur.length <= 1) return fail('INVALID_ARGS', 'Lista nie może być pusta.'); const l = J.market.setWatch(cur.filter(x => x !== alias)); return ok({ symbols: l }, 'Usunąłem ' + alias + ' z obserwowanych.', null, () => J.market.setWatch(cur));
  } });
R.add({ id: 'market_alerts', group: 'Dane', label: 'Alerty kursów', description: 'Lista alertów kursów (list), usunięcie jednego (remove, alert = symbol albo id) albo wszystkich (clear).', writes: ['alerts'],
  args: { type: 'object', properties: { op: { type: 'string', enum: ['list', 'remove', 'clear'] }, alert: { type: 'string' } }, required: ['op'] },
  examples: ['jakie mam alerty kursow', 'pokaz alerty kursow', 'usun alert na {alert}', 'wyczysc alerty kursow', 'usun wszystkie powiadomienia o cenach'],
  parse(raw, n) { let m; if (/^(pokaz )?alerty kursow$|^jakie mam alerty kursow$/.test(n)) return { args: { op: 'list' }, score: 35 }; if ((m = /^usun alert (?:na|dla)\s+(.+)$/.exec(n))) return { args: { op: 'remove', alert: m[1] }, score: 35 }; if (/^(wyczysc|usun) (wszystkie )?(alerty kursow|powiadomienia o cenach)$/.test(n)) return { args: { op: 'clear' }, score: 35 }; return null; },
  run({ op, alert }) { const al = J.state.alerts = J.state.alerts || [], prev = al.slice(); const fmt = a => a.symbol + ' ' + (a.direction === 'above' ? '>' : '<') + ' ' + J.fmtMoney(a.price); if (op === 'list') return ok({ alerts: al }, al.length ? 'Alerty: ' + al.map(fmt).join(', ') + '.' : 'Brak alertów kursów.'); const restore = () => { J.state.alerts = prev; J.save(); }; if (op === 'clear') { if (!al.length) return ok(null, 'Brak alertów.'); J.state.alerts = []; J.save(); return ok({ removed: prev.length }, 'Usunąłem wszystkie alerty (' + prev.length + ').', null, restore); } const sym = (J.cmdKit.coinOf?.(alert) || String(alert || '')).toUpperCase(); const hit = al.filter(a => a.id === alert || a.symbol === sym); if (!hit.length) return fail('NOT_FOUND', 'Nie ma alertu „' + alert + '”.'); J.state.alerts = al.filter(a => !hit.includes(a)); J.save(); return ok({ removed: hit.length }, 'Usunąłem: ' + hit.map(fmt).join(', ') + '.', null, restore); } });
undoable(['market_watchlist', 'market_alerts']);

/* =================== PAMIĘĆ =================== */
R.add({ id: 'memory_edit', group: 'Pamięć', label: 'Popraw zapamiętany fakt', description: 'Zmienia treść zapamiętanego faktu (fact = id albo fragment, text = nowa treść).', writes: ['memory'],
  args: { type: 'object', properties: { fact: { type: 'string' }, text: { type: 'string', maxLength: 300 } }, required: ['fact', 'text'] },
  examples: ['popraw w pamieci {fact} na {text}', 'zmien fakt o {fact} na {text}', 'popraw fakt {fact}: {text}'],
  parse(raw, n) { let m; if ((m = /^(?:popraw|zmien)(?: w pamieci| fakt(?: o)?| w pamieci fakt(?: o)?)\s+(.+?)\s+na\s+(.+)$/.exec(n)) && !/notatk|zadani|skrot|uklad|watk/.test(m[1])) return { args: { fact: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length), text: raw.slice(n.lastIndexOf(m[2])) }, score: 30 }; if ((m = /^popraw fakt(?: o)?\s+(.+?)(?: w pamieci)?$/.exec(n))) return { args: { fact: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length) }, score: 30 }; return null; },
  async run({ fact, text }) { if (J.policy.sensitive(text).flagged) return fail('DENIED', 'To wygląda na poufną informację — nie zapiszę jej w pamięci.'); const l = await J.memory.all(), q = norm(fact); const f = l.find(x => x.id === fact) || l.find(x => norm(x.fact).includes(q)) || l.find(x => q.split(' ').filter(w => w.length > 3).some(w => norm(x.fact).includes(w))); if (!f) return fail('NOT_FOUND', 'Nie pamiętam niczego o „' + fact + '”.'); const prev = f.fact; await J.memory.update(f.id, text); return ok({ id: f.id, fact: text }, 'Poprawiłem: „' + prev + '” → „' + text + '”.', null, () => J.memory.update(f.id, prev)); } });
undoable(['memory_edit']);

/* =================== PLIKI =================== */
R.add({ id: 'files_open', group: 'Pliki', label: 'Pokaż plik', description: 'Otwiera podgląd pliku (tekst, Markdown, JSON, CSV, obraz) w oknie Pliki.', idempotent: true, reads: ['files'], writes: ['windows'],
  args: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] },
  examples: ['pokaz plik {path}', 'podglad pliku {path}', 'pokaz co jest w pliku {path}'],
  parse(raw, n) { const m = /^(?:pokaz|podglad|otworz podglad|otworz)(?: co jest w)?\s+(?:plik|pliku)\s+(\S+\.\w{1,5})$/.exec(n); return m ? { args: { path: raw.slice(n.lastIndexOf(m[1])) }, score: 30 } : null; },
  async run({ path }) { J.wm.open('files', { view: 'path', target: path }); return ok({ path }, 'Pliki: ' + path + '.', { highlight: 'files' }); } });

/* =================== DOK I WIDGETY =================== */
R.add({ id: 'dock_order', group: 'Pulpit i widgety', label: 'Kolejność w doku', description: 'Przesuwa aplikację w doku na pozycję (1 = pierwsza).', writes: ['settings'],
  args: { type: 'object', properties: { item: { type: 'string', description: 'id aplikacji' }, position: { type: 'integer', minimum: 1, maximum: 30 } }, required: ['item', 'position'] },
  examples: ['przesun {item} na (poczatek|koniec) doku', '{item} na (pierwsze|drugie|trzecie|ostatnie) miejsce w doku', 'daj {item} na drugie miejsce'],
  parse(raw, n) { const m = /^(?:przesun\s+|daj\s+)?(.+?)\s+(?:na|jako)\s+(poczatek|koniec|pierwsz\w*|drugi\w*|trzeci\w*|czwart\w*|ostatni\w*)(?: miejsce)?(?: w doku| doku)?$/.exec(n); if (!m || !/dok/.test(n)) return null; const app = J.findApp(m[1]); if (!app) return null; const pos = /^(poczatek|pierwsz)/.test(m[2]) ? 1 : /^drug/.test(m[2]) ? 2 : /^trzec/.test(m[2]) ? 3 : /^czwart/.test(m[2]) ? 4 : 30; return { args: { item: app, position: pos }, score: 30 }; },
  run({ item, position }) { const app = J.apps[item] ? item : J.findApp(item); if (!app) return fail('NOT_FOUND', 'Nie ma aplikacji „' + item + '”.'); const s = J.state.settings, prev = [...(s.dockOrder || [])]; const base = (s.dockOrder && s.dockOrder.length ? s.dockOrder : J.DOCK_DEFAULT || []).filter(x => x !== app); base.splice(J.clamp(position - 1, 0, base.length), 0, app); s.dockOrder = base; J.save(); J.emit('wm'); return ok({ order: base }, J.APP_NAMES[app] + ' na miejscu ' + (base.indexOf(app) + 1) + ' w doku.', null, () => { s.dockOrder = prev; J.save(); J.emit('wm'); }); } });
const findWidget = q => { const v = String(q || ''); if (/^(current|ten|tego|ten widget)$/.test(norm(v))) { const f = J.wm.focused(); return f?.startsWith('w:') ? J.widgets.list.find(w => 'w:' + w.id === f) : null; } const n = norm(v); return J.widgets.list.find(w => w.id === v || 'w:' + w.id === v) || J.widgets.list.find(w => norm(w.title) === n) || J.widgets.list.find(w => norm(w.title).includes(n)); };
J.cmdKit.findWidget = findWidget;
R.add({ id: 'widget_duplicate', group: 'Pulpit i widgety', label: 'Duplikuj widget', description: 'Tworzy kopię widgetu obok oryginału.', writes: ['widgets'],
  args: { type: 'object', properties: { widget: { type: 'string', description: 'id albo tytuł; "current" = aktywny' } }, required: ['widget'] },
  examples: ['zduplikuj widget {widget}', 'duplikuj widget {widget}', 'zrob kopie widgetu {widget}', 'zduplikuj ten widget'],
  parse(raw, n) { const m = /^(?:zduplikuj|duplikuj|skopiuj)\s+(?:ten widget|widget\s+(.+))$|^zrob (?:kopie widgetu|drugi taki sam widget)\s*(.*)$/.exec(n); return m ? { args: { widget: m[1] || m[2] || 'current' }, score: 35 } : null; },
  run({ widget }) { const w = findWidget(widget); if (!w) return fail('NOT_FOUND', 'Nie ma widgetu „' + widget + '”.'); const c = J.widgets.duplicate(w.id); return ok({ id: c.id, title: c.title }, 'Zrobiłem kopię widgetu „' + w.title + '”.', { highlight: 'w:' + c.id }, () => J.widgets.remove(c.id, { silent: true })); } });
R.add({ id: 'widget_collapse', group: 'Pulpit i widgety', label: 'Zwiń / rozwiń widget', description: 'Zwija widget do paska tytułu albo rozwija (on). widget="all" — wszystkie.', writes: ['widgets'],
  args: { type: 'object', properties: { widget: { type: 'string' }, on: { type: 'boolean' } }, required: ['widget'] },
  examples: ['zwin widget {widget}', 'rozwin widget {widget}', 'zwin wszystkie widgety', 'schowaj zawartosc tego widgetu'],
  parse(raw, n) { let m; if (/^zwin wszystkie widgety$/.test(n)) return { args: { widget: 'all', on: true }, score: 35 }; if (/^rozwin wszystkie widgety$/.test(n)) return { args: { widget: 'all', on: false }, score: 35 }; if ((m = /^(zwin|rozwin)\s+(?:widget\s+)?(.+)$/.exec(n)) && findWidget(m[2])) return { args: { widget: raw.slice(n.lastIndexOf(m[2])), on: m[1] === 'zwin' }, score: 35 }; if (/^schowaj zawartosc tego widgetu$/.test(n)) return { args: { widget: 'current', on: true }, score: 30 }; return null; },
  run({ widget, on = true }) { const l = widget === 'all' ? J.widgets.list.slice() : [findWidget(widget)].filter(Boolean); if (!l.length) return fail('NOT_FOUND', 'Nie ma widgetu „' + widget + '”.'); const prev = l.map(w => [w, !!w.collapsed]); l.forEach(w => J.widgets.collapse(w.id, on)); return ok({ widgets: l.map(w => w.id) }, (on ? 'Zwinąłem ' : 'Rozwinąłem ') + (l.length > 1 ? l.length + ' widgetów' : '„' + l[0].title + '”') + '.', null, () => prev.forEach(([w, c]) => J.widgets.collapse(w.id, c))); } });
R.add({ id: 'widget_items', group: 'Pulpit i widgety', label: 'Pozycje listy w widgecie', description: 'Na widgecie-liście: dodaje (add), odhacza (check), odznacza (uncheck), zmienia (rename → to), usuwa (remove) pozycję albo usuwa odhaczone (clear_done).', writes: ['widgets'],
  args: { type: 'object', properties: { widget: { type: 'string' }, op: { type: 'string', enum: ['add', 'check', 'uncheck', 'rename', 'remove', 'clear_done'] }, item: { type: 'string' }, to: { type: 'string' } }, required: ['widget', 'op'] },
  examples: ['dopisz {item} do listy {widget}', 'odhacz {item} na liscie {widget}', 'usun zrobione z listy {widget}'],
  parse(raw, n) { let m; if ((m = /^(?:dodaj|dopisz)\s+(.+?)\s+do listy\s+(.+)$/.exec(n)) && findWidget(m[2])) return { args: { widget: raw.slice(n.lastIndexOf(m[2])), op: 'add', item: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length) }, score: 40 }; if ((m = /^odhacz\s+(.+?)\s+na liscie\s+(.+)$/.exec(n)) && findWidget(m[2])) return { args: { widget: raw.slice(n.lastIndexOf(m[2])), op: 'check', item: raw.slice(n.indexOf(m[1]), n.indexOf(m[1]) + m[1].length) }, score: 40 }; if ((m = /^usun (?:zrobione|odhaczone) z listy\s+(.+)$/.exec(n)) && findWidget(m[1])) return { args: { widget: raw.slice(n.lastIndexOf(m[1])), op: 'clear_done' }, score: 40 }; return null; },
  run({ widget, op, item, to }) { const w = findWidget(widget); if (!w) return fail('NOT_FOUND', 'Nie ma widgetu „' + widget + '”.'); if (w.type !== 'list') return fail('INVALID_ARGS', '„' + w.title + '” nie jest listą.'); const items = w.data.items, prev = JSON.parse(JSON.stringify(items)); const q = norm(item || ''), it = items.find(i => norm(i.text) === q) || items.find(i => q && norm(i.text).includes(q));
    if (op === 'add') { if (!item) return fail('INVALID_ARGS', 'Co dopisać?'); items.push({ text: String(item).trim(), done: false }); }
    else if (op === 'clear_done') { w.data.items = items.filter(i => !i.done); }
    else { if (!it) return fail('NOT_FOUND', 'Na liście „' + w.title + '” nie ma „' + item + '”.'); if (op === 'check' || op === 'uncheck') it.done = op === 'check'; else if (op === 'rename') { if (!to) return fail('INVALID_ARGS', 'Na co zmienić?'); it.text = to; } else w.data.items = items.filter(i => i !== it); }
    J.save(); J.widgets.refresh(w.id); return ok({ id: w.id, items: w.data.items.length }, '„' + w.title + '”: ' + ({ add: 'dopisałem', check: 'odhaczyłem', uncheck: 'odznaczyłem', rename: 'zmieniłem', remove: 'usunąłem', clear_done: 'usunąłem zrobione' }[op]) + (item ? ' „' + item + '”' : '') + '.', { highlight: 'w:' + w.id }, () => { w.data.items = prev; J.save(); J.widgets.refresh(w.id); }); } });
undoable(['dock_order', 'widget_duplicate', 'widget_collapse', 'widget_items']);
})();
