#!/usr/bin/env python3
"""
vault_stats.py — Obsidian Vault Statistics

Oblicza statystyki vaultu i aktualizuje index.md.

Użycie:
    python vault_stats.py --vault /path/to/vault
    python vault_stats.py --vault /path/to/vault --json
    python vault_stats.py --vault /path/to/vault --print-only
"""

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):   # konsola/cron na Windows = cp1250, a skrypt drukuje emoji
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
EXCLUDED_FOLDERS = {"templates", "references", ".obsidian", ".trash", ".claude", "raw", "__pycache__"}
STATS_BEGIN = "<!-- BEGIN STATS - generated by vault_stats.py -->"
STATS_END = "<!-- END STATS -->"


def parse_frontmatter(text: str) -> dict:
    """Lightweight YAML frontmatter parser."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        line = line.rstrip()
        if not line or line.startswith("#") or line.startswith(" ") or line.startswith("-"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        val = val.strip().strip('"').strip("'")
        fm[key.strip()] = val
    return fm


def compute_stats(vault: Path) -> dict:
    """Compute vault statistics."""
    type_counts = Counter()
    status_counts = Counter()
    tag_counts = Counter()
    total_notes = 0
    total_links = 0
    total_words = 0
    oldest_note = None
    newest_note = None

    link_pattern = re.compile(r"\[\[([^\]]+)\]\]")

    for f in vault.rglob("*.md"):
        parts = {part.lower() for part in f.relative_to(vault).parts}
        if parts & EXCLUDED_FOLDERS:
            continue

        try:
            content = f.read_text(encoding="utf-8")
        except Exception:
            continue

        total_notes += 1
        fm = parse_frontmatter(content)

        # Type counts
        note_type = fm.get("type", "uncategorized")
        type_counts[note_type] += 1

        # Status counts
        status = fm.get("status", "unknown")
        status_counts[status] += 1

        # Tag counts
        tags_str = fm.get("tags", "")
        if tags_str:
            # Handle both list format [a, b] and comma-separated
            if tags_str.startswith("["):
                tags = [t.strip().strip("[]'\"") for t in tags_str.split(",")]
            else:
                tags = [t.strip() for t in tags_str.split(",")]
            for t in tags:
                if t:
                    tag_counts[t] += 1

        # Links
        links = link_pattern.findall(content)
        total_links += len(links)

        # Words (rough count)
        text_content = re.sub(r"\[\[.*?\]\]", "", content)
        text_content = re.sub(r"<%.*?%>", "", text_content)
        text_content = re.sub(r"```.*?```", "", text_content, flags=re.DOTALL)
        total_words += len(text_content.split())

        # Dates
        date_str = fm.get("date", fm.get("created", ""))
        if date_str:
            try:
                note_date = date.fromisoformat(date_str[:10])
                if oldest_note is None or note_date < oldest_note:
                    oldest_note = note_date
                if newest_note is None or note_date > newest_note:
                    newest_note = note_date
            except ValueError:
                pass

    return {
        "total_notes": total_notes,
        "total_links": total_links,
        "total_words": total_words,
        "type_counts": dict(type_counts.most_common()),
        "status_counts": dict(status_counts.most_common()),
        "top_tags": dict(tag_counts.most_common(10)),
        "oldest_note": str(oldest_note) if oldest_note else "N/A",
        "newest_note": str(newest_note) if newest_note else "N/A",
        "scan_date": str(date.today()),
    }


def format_stats_block(stats: dict) -> str:
    """Format stats as markdown block for index.md."""
    lines = [
        STATS_BEGIN,
        "",
        f"**Skan:** {stats['scan_date']}",
        "",
        "| Metryka | Wartość |",
        "|---------|---------|",
        f"| Notatki | {stats['total_notes']} |",
        f"| Linki wewnętrzne | {stats['total_links']} |",
        f"| Słowa | {stats['total_words']:,} |",
        f"| Najstarsza notatka | {stats['oldest_note']} |",
        f"| Najnowsza notatka | {stats['newest_note']} |",
        "",
        "**Typy notatek:**",
    ]

    for t, c in stats["type_counts"].items():
        lines.append(f"- {t}: {c}")

    lines.append("")
    lines.append("**Statusy:**")
    for s, c in stats["status_counts"].items():
        lines.append(f"- {s}: {c}")

    if stats["top_tags"]:
        lines.append("")
        lines.append("**Top tagi:**")
        for tag, c in stats["top_tags"].items():
            lines.append(f"- {tag}: {c}")

    lines.append("")
    lines.append(STATS_END)
    return "\n".join(lines)


def update_index_md(vault: Path, stats_block: str):
    """Update the stats block in index.md."""
    index_path = vault / "index.md"
    if not index_path.exists():
        return

    content = index_path.read_text(encoding="utf-8")

    # Replace existing stats block
    pattern = re.compile(
        re.escape(STATS_BEGIN) + r".*?" + re.escape(STATS_END),
        re.DOTALL,
    )
    if pattern.search(content):
        new_content = pattern.sub(stats_block, content)
    else:
        # Append at end
        new_content = content.rstrip() + "\n\n" + stats_block

    index_path.write_text(new_content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Obsidian Vault Statistics")
    parser.add_argument("--vault", required=True, help="Path to vault")
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument("--print-only", action="store_true", help="Print only, don't write")
    args = parser.parse_args()

    vault = Path(args.vault)
    if not vault.exists():
        print(f"Error: Vault not found: {args.vault}", file=sys.stderr)
        sys.exit(1)

    stats = compute_stats(vault)

    if args.json:
        print(json.dumps(stats, indent=2, ensure_ascii=False))
        return

    stats_block = format_stats_block(stats)

    if args.print_only:
        print(stats_block)
    else:
        update_index_md(vault, stats_block)
        print(f"Stats updated in {vault / 'index.md'}")
        print(f"Total notes: {stats['total_notes']}")
        print(f"Total links: {stats['total_links']}")
        print(f"Total words: {stats['total_words']:,}")


if __name__ == "__main__":
    main()
